server:
  port: 9000
spring:
  application:
    name: "orders"
  profiles:
     active: "prod"
  datasource:
    url: jdbc:mysql://localhost:3308/ordersdb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: "optional:configserver:http://localhost:8071/"
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
build:
  version: "3.0"

orders :
  message: "Welcome to CartWorks orders related local APIs "
  contactDetails:
    name: "Yaron Olivcovitz - Product Owner"
    email: "yaron.olivcovitz@cartworks.com"
  onCallSupport:
    - (058) 565-9890
    - (054) 441-323


