spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

orders:
  message: "Welcome to CartWorks users related prod APIs "
  contactDetails:
    name: "Gali Olivcovitz - Product Owner"
    email: "gali.olivcovitz@cartworks.com"
  onCallSupport:
    - (054) 533-6330
    - (053) 431-1234