spring:
  profiles:
    active: qa
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    initialize: true
  h2:
    console:
      enabled: true

logging:
  level:
    root: INFO
    com.cartworks: DEBUG
