server:
  port: 8090
spring:
  application:
    name: "products"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:mysql://localhost:3307/productsdb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: "optional:configserver:http://localhost:8071/"
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

build:
  version: "3.0"

products:
  message: "Welcome to CartWorks products related local APIs"
  contactDetails:
    name: "Yaron Olivcovitz - Product Owner"
    email: "yaron.olivcovitz@cartworks.com"
  onCallSupport:
    - (058) 565-9890
    - (054) 441-323


management:
  endpoints:
    web:
      exposure:
        include: "*"