
spring:
  application:
    name: "configserver"
  profiles:
    #active: native
    active: git
  cloud:
    config:
      server:
        native:
        search-locations: "classpath:/config"
        git:
          uri: "https://github.com/ItayOlivcovitz/cartworks-config"
          default-label: "main"
          timeout: 5
          clone-on-start: true
          force-pull: true

encrypt:
  key: "Qa8MUxFAxvm8udUJJz4BOtCgojlD5z7HkbySJ6uC11I="


server:
  port: 8071