services:
  rabbit:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    networks:
      - cartworks

  configserver:
    image: "itayolivcovitz/configserver:s8"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    depends_on:
      rabbit:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
        file: common-config.yml
        service: microservice-base-config

  eurekaserver:
    image: "itayolivcovitz/eurekaserver:s8"
    container_name: eurekaserver-ms
    ports:
      - "8070:8070"
    depends_on:
      configserver:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-configserver-config
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"

  usersdb:
    image: mysql
    container_name: usersdb
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: usersdb
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root --silent"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - cartworks

  users:
    image: "itayolivcovitz/users:s8"
    container_name: users-ms
    ports:
      - "8080:8080"
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
          condition: service_healthy
      usersdb:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "users"
      SPRING_DATASOURCE_URL: "jdbc:mysql://usersdb:3306/usersdb"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  ordersdb:
    image: mysql
    container_name: ordersdb
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: ordersdb
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root --silent"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - cartworks

  orders:
    image: "itayolivcovitz/orders:s8"
    container_name: orders-ms
    ports:
      - "9000:9000"

    depends_on:
      ordersdb:
        condition: service_healthy
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    environment:
        SPRING_DATASOURCE_URL: "jdbc:mysql://ordersdb:3306/ordersdb"
        SPRING_APPLICATION_NAME: "orders"
    extends:
          file: common-config.yml
          service: microservice-eureka-config

  productsdb:
    image: mysql
    container_name: productsdb
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: productsdb
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root --silent"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - cartworks

  products:
    image: "itayolivcovitz/products:s8"
    container_name: products-ms
    ports:
      - "8090:8090"
    environment:
      SPRING_APPLICATION_NAME: "products"
      SPRING_DATASOURCE_URL: "jdbc:mysql://productsdb:3306/productsdb"
    depends_on:
      productsdb:
        condition: service_healthy
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-eureka-config

networks:
  cartworks:
    driver: bridge
